- name: Update package cache and upgrade (Debian)
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == 'Debian'

- name: Update package cache and upgrade (RedHat)
  ansible.builtin.dnf:
    update_cache: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install essential packages (Debian)
  ansible.builtin.apt:
    name:
      - curl-minimal
      - git
      - unzip
      - python3-pip
      - ca-certificates
      - gnupg
    state: present
  when: ansible_os_family == 'Debian'

- name: Install essential packages (RedHat)
  ansible.builtin.dnf:
    name:
      - curl-minimal
      - git
      - unzip
      - python3-pip
    state: present
  when: ansible_facts['os_family'] == 'RedHat'
