name: create infrastructure using terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform (apply or destroy)"
        required: true
        default: "apply"

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -var="db_username=${{ secrets.DB_USERNAME }}" -var="db_password=${{ secrets.DB_PASSWORD }}" -var="github_repo=${{ github.repository }}" -out=plan.out

      - name: save plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/plan.out

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform -chdir=terraform apply -auto-approve plan.out

      - name: Get EC2 Public IP
        if: ${{ github.event.inputs.action == 'apply' }}
        id: terraform_output
        run: |
          IP=$(terraform -chdir=terraform output -raw ec2_public_ip)
          echo "ec2_ip=$IP" >> $GITHUB_OUTPUT

      - name: Trigger Configure VM workflow
        if: ${{ github.event.inputs.action == 'apply' }}
        uses: actions/github-script@v7
        env:
          EC2_IP: ${{ steps.terraform_output.outputs.ec2_ip }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ec2Host = process.env.EC2_IP;
            console.log(`Triggering configure-vm with EC2 host: ${ec2Host}`);
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'configure-vm.yml',
              ref: 'main',
              inputs: {
                ec2_host: ec2Host
              }
            });

      - name: Terraform destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform -chdir=terraform destroy -auto-approve -var="db_username=${{ secrets.DB_USERNAME }}" -var="db_password=${{ secrets.DB_PASSWORD }}" -var="github_repo=${{ github.repository }}"
